### ISSUE TITLE
Set repository default branch to 'source'

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/omnilayer.github.io#1]
This should default to displaying the `source` branch when users visit the Github project page.

(I'm not sure what else is affected by the *default branch* setting.)

**Comment by msgilligan** [comment]
It looks like all effects of the *default branch* setting are positive for this use case:
https://help.github.com/articles/setting-the-default-branch/

**Comment by achamely** [comment]
Updated

**Comment by msgilligan** [comment]
Thanks!
