### ISSUE TITLE
Choose and assign a custom domain.

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/omnilayer.github.io#5]
This site should have a [custom domain](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/).

Suggestions:

* `dev.omnilayer.org`
* `github.omnilayer.org`

or, if we think this can be used to replace the current site:

* [www.omnilayer.org](http://www.omnilayer.org)

**Comment by dexX7** [comment]
At some point it should probably replace omnilayer.org.

**Comment by msgilligan** [comment]
Thanks, @dexX7. That's my goal, but I'm going to need help with the design and approval from the rest of the team.
